import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const SEED_USERS = [
  // ==================== BRAZIL BATCH 2 (30) ====================
  // Photographers BR (10)
  { email: 'vinicius.photo@seed.castlight.app', name: 'Vinícius Cardoso', role: 'photographer', city: 'São Paulo', state: 'SP', country: 'BR', bio: 'Fotógrafo de moda urbana e streetwear. Minhas referências vão do hip-hop ao brutalismo. Sempre buscando modelos com atitude.', styles: ['Fashion', 'Street', 'Editorial', 'Commercial'], instagram: '@viniciuscardosoph', avatar_url: 'https://images.unsplash.com/photo-1618886614638-80e3c103d31a?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'premium', verified_level: 'email', rating_avg: 4.6, total_reviews: 17, total_sessions: 21, equipment: ['Canon EOS R3', 'RF 24-70mm f/2.8'], has_studio: false, languages: ['Portuguese', 'English'] },
  { email: 'tatiana.reis.ph@seed.castlight.app', name: 'Tatiana Reis', role: 'photographer', city: 'Niterói', state: 'RJ', country: 'BR', bio: 'Fotógrafa de ensaios femininos e empoderamento. Cada clique é um ato de amor próprio. Mulheres reais, fotos reais. 💜', styles: ['Portrait', 'Boudoir', 'Beauty', 'Lifestyle'], instagram: '@tatianareisph', avatar_url: 'https://images.unsplash.com/photo-1593104547489-5cfb3839a3b5?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'pro', verified_level: 'identity', rating_avg: 4.9, total_reviews: 34, total_sessions: 43, equipment: ['Sony A7III', 'GM 85mm f/1.4', 'Godox V1'], has_studio: true, languages: ['Portuguese'] },
  { email: 'anderson.lima.ph@seed.castlight.app', name: 'Anderson Lima', role: 'photographer', city: 'Fortaleza', state: 'CE', country: 'BR', bio: 'Fotógrafo de moda e catálogo. Nordeste na veia! Trabalho com marcas locais e nacionais. Estúdio completo com ciclorama.', styles: ['Fashion', 'Commercial', 'Beauty', 'Editorial'], instagram: '@andersonlimaph', avatar_url: 'https://images.unsplash.com/photo-1603415526960-f7e0328c63b1?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'pro', verified_level: 'email', rating_avg: 4.7, total_reviews: 26, total_sessions: 32, equipment: ['Nikon D850', 'Sigma 50mm Art', 'Elinchrom D-Lite'], has_studio: true, languages: ['Portuguese'] },
  { email: 'patricia.gomes.ph@seed.castlight.app', name: 'Patrícia Gomes', role: 'photographer', city: 'Vitória', state: 'ES', country: 'BR', bio: 'Fotógrafa de casais e pré-wedding. Capturo o amor como ele é: espontâneo, real e cheio de emoção. Aceito TFP para portfólio.', styles: ['Couples', 'Lifestyle', 'Portrait', 'Events'], instagram: '@patriciagomesph', avatar_url: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'free', verified_level: 'email', rating_avg: 4.5, total_reviews: 11, total_sessions: 14, equipment: ['Canon R6', 'RF 35mm f/1.8'], has_studio: false, languages: ['Portuguese'] },
  { email: 'marcos.teixeira.ph@seed.castlight.app', name: 'Marcos Teixeira', role: 'photographer', city: 'Belém', state: 'PA', country: 'BR', bio: 'Fotógrafo documental e retratista amazônico. Capturo a beleza do Norte do Brasil com olhar autoral. Projetos sociais e editoriais.', styles: ['Portrait', 'Fine Art', 'Street', 'Conceptual'], instagram: '@marcosteixeiraph', avatar_url: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?w=400&h=400&fit=crop&crop=face', user_level: 'starter', plan: 'free', verified_level: 'email', rating_avg: 4.4, total_reviews: 8, total_sessions: 10, equipment: ['Fujifilm X-Pro3', 'XF 35mm f/1.4'], has_studio: false, languages: ['Portuguese'] },
  { email: 'renato.barros.ph@seed.castlight.app', name: 'Renato Barros', role: 'photographer', city: 'Campo Grande', state: 'MS', country: 'BR', bio: 'Fotógrafo de natureza e retratos outdoor. Mato Grosso do Sul é pura inspiração. Ensaios em cachoeiras, rios e cerrado.', styles: ['Lifestyle', 'Portrait', 'Fine Art', 'Couples'], instagram: '@renatobarrosph', avatar_url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'premium', verified_level: 'email', rating_avg: 4.6, total_reviews: 13, total_sessions: 16, equipment: ['Sony A7C', 'FE 55mm f/1.8'], has_studio: false, languages: ['Portuguese', 'Spanish'] },
  { email: 'daniela.moura.ph@seed.castlight.app', name: 'Daniela Moura', role: 'photographer', city: 'Ribeirão Preto', state: 'SP', country: 'BR', bio: 'Fotógrafa de gestante e família. Cada barriga conta uma história linda. Ensaios delicados em estúdio e ao ar livre. 🤰', styles: ['Maternity', 'Portrait', 'Lifestyle', 'Beauty'], instagram: '@danielamouraph', avatar_url: 'https://images.unsplash.com/photo-1586297135537-94bc9ba060aa?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'premium', verified_level: 'email', rating_avg: 4.8, total_reviews: 30, total_sessions: 37, equipment: ['Canon R5', 'RF 70-200mm f/2.8'], has_studio: true, languages: ['Portuguese'] },
  { email: 'igor.souza.ph@seed.castlight.app', name: 'Igor Souza', role: 'photographer', city: 'Cuiabá', state: 'MT', country: 'BR', bio: 'Fotógrafo de eventos e retratos corporativos. Também faço ensaios pessoais e editoriais. Profissional dedicado e criativo.', styles: ['Events', 'Portrait', 'Commercial', 'Lifestyle'], instagram: '@igorsouzaph', avatar_url: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=400&h=400&fit=crop&crop=face', user_level: 'starter', plan: 'free', verified_level: 'none', rating_avg: 4.2, total_reviews: 5, total_sessions: 7, equipment: ['Nikon Z5', 'Nikkor 50mm f/1.8'], has_studio: false, languages: ['Portuguese'] },
  { email: 'adriana.pinto.ph@seed.castlight.app', name: 'Adriana Pinto', role: 'photographer', city: 'São Luís', state: 'MA', country: 'BR', bio: 'Fotógrafa editorial e de beleza afro. Celebro a diversidade e a cultura negra através das minhas lentes. Representatividade sempre! ✊🏿', styles: ['Beauty', 'Editorial', 'Fashion', 'Portrait'], instagram: '@adrianapintoph', avatar_url: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'free', verified_level: 'email', rating_avg: 4.7, total_reviews: 15, total_sessions: 19, equipment: ['Canon EOS R', 'RF 50mm f/1.8', 'Godox AD300'], has_studio: false, languages: ['Portuguese', 'French'] },
  { email: 'caio.ramos.ph@seed.castlight.app', name: 'Caio Ramos', role: 'photographer', city: 'Joinville', state: 'SC', country: 'BR', bio: 'Fotógrafo de arquitetura e interiores que migrou pro retrato. Composições limpas, iluminação técnica e atenção aos detalhes.', styles: ['Portrait', 'Commercial', 'Editorial', 'Fine Art'], instagram: '@caioramosph', avatar_url: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'premium', verified_level: 'email', rating_avg: 4.5, total_reviews: 10, total_sessions: 13, equipment: ['Sony A7RIV', 'Sigma 24-70mm Art'], has_studio: true, languages: ['Portuguese', 'English'] },

  // Models BR (12)
  { email: 'bianca.santos.md@seed.castlight.app', name: 'Bianca Santos', role: 'model', city: 'São Paulo', state: 'SP', country: 'BR', bio: 'Modelo comercial e de passarela. 1.78m. 5 anos de experiência. Trabalho com as principais marcas de fast fashion do Brasil.', styles: ['Fashion', 'Commercial', 'Editorial', 'Lifestyle'], instagram: '@biancasantosmd', avatar_url: 'https://images.unsplash.com/photo-1503104834685-7205e8607eb9?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'pro', verified_level: 'identity', rating_avg: 4.8, total_reviews: 31, total_sessions: 39, measurements: '{"height":"178","bust":"86","waist":"62","hips":"90","shoes":"39","eyes":"Brown","hair":"Black"}' },
  { email: 'paulo.vieira.md@seed.castlight.app', name: 'Paulo Vieira', role: 'model', city: 'Rio de Janeiro', state: 'RJ', country: 'BR', bio: 'Modelo masculino e surfista. 1.85m. Ensaios de moda praia, lifestyle e fitness. Carioca raiz, energia boa sempre! 🤙', styles: ['Fitness', 'Lifestyle', 'Fashion', 'Commercial'], instagram: '@paulovieiramd', avatar_url: 'https://images.unsplash.com/photo-1583195764036-6dc248ac07d9?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'premium', verified_level: 'email', rating_avg: 4.6, total_reviews: 14, total_sessions: 18, measurements: '{"height":"185","bust":"100","waist":"78","hips":"96","shoes":"43","eyes":"Green","hair":"Brown"}' },
  { email: 'julia.freitas.md@seed.castlight.app', name: 'Júlia Freitas', role: 'model', city: 'Curitiba', state: 'PR', country: 'BR', bio: 'Modelo de beauty e skincare. Rosto versátil, pele cuidada. Ideal para campanhas de cosméticos e cuidados pessoais. Aceito TFP!', styles: ['Beauty', 'Commercial', 'Fashion', 'Portrait'], instagram: '@juliafreitasmd', avatar_url: 'https://images.unsplash.com/photo-1504703395950-b89145a5425b?w=400&h=400&fit=crop&crop=face', user_level: 'starter', plan: 'free', verified_level: 'email', rating_avg: 4.4, total_reviews: 9, total_sessions: 12, measurements: '{"height":"167","bust":"82","waist":"62","hips":"88","shoes":"36","eyes":"Brown","hair":"Brown"}' },
  { email: 'thais.oliveira.md@seed.castlight.app', name: 'Thaís Oliveira', role: 'model', city: 'Salvador', state: 'BA', country: 'BR', bio: 'Modelo e dançarina afro-brasileira. Meu corpo conta histórias de ancestralidade e força. Ensaios com propósito e arte. ✊🏾', styles: ['Conceptual', 'Editorial', 'Fine Art', 'Fashion'], instagram: '@thaisolivmd', avatar_url: 'https://images.unsplash.com/photo-1523824921871-d6f1a15151f1?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'premium', verified_level: 'email', rating_avg: 4.7, total_reviews: 17, total_sessions: 22, measurements: '{"height":"172","bust":"88","waist":"66","hips":"96","shoes":"38","eyes":"Brown","hair":"Black"}' },
  { email: 'gustavo.melo.md@seed.castlight.app', name: 'Gustavo Melo', role: 'model', city: 'Brasília', state: 'DF', country: 'BR', bio: 'Modelo fitness e personal trainer. 1.82m. Corpo atlético, disciplinado. Campanhas de sportswear e suplementos. Disponível para TFP.', styles: ['Fitness', 'Commercial', 'Portrait', 'Lifestyle'], instagram: '@gustavomelofit', avatar_url: 'https://images.unsplash.com/photo-1480455624313-e29b44bbfde1?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'free', verified_level: 'email', rating_avg: 4.5, total_reviews: 12, total_sessions: 15, measurements: '{"height":"182","bust":"104","waist":"76","hips":"96","shoes":"42","eyes":"Brown","hair":"Black"}' },
  { email: 'mariana.castro.md@seed.castlight.app', name: 'Mariana Castro', role: 'model', city: 'Goiânia', state: 'GO', country: 'BR', bio: 'Modelo de lingerie e moda íntima. Trabalho com marcas de underwear e sleepwear. Profissionalismo e discrição garantidos.', styles: ['Boudoir', 'Fashion', 'Commercial', 'Beauty'], instagram: '@marianacastromd', avatar_url: 'https://images.unsplash.com/photo-1499557354967-2b2d8910bcca?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'premium', verified_level: 'identity', rating_avg: 4.8, total_reviews: 24, total_sessions: 30, measurements: '{"height":"174","bust":"88","waist":"62","hips":"92","shoes":"37","eyes":"Green","hair":"Blonde"}' },
  { email: 'eduardo.silva.md@seed.castlight.app', name: 'Eduardo Silva', role: 'model', city: 'Porto Alegre', state: 'RS', country: 'BR', bio: 'Modelo editorial e de catálogo. 1.88m. Look clássico e versátil. Experiência com moda masculina, acessórios e relógios.', styles: ['Fashion', 'Editorial', 'Commercial', 'Portrait'], instagram: '@eduardosilvamd', avatar_url: 'https://images.unsplash.com/photo-1492446845049-9c50cc313f00?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'pro', verified_level: 'identity', rating_avg: 4.9, total_reviews: 33, total_sessions: 41, measurements: '{"height":"188","bust":"100","waist":"78","hips":"96","shoes":"44","eyes":"Blue","hair":"Brown"}' },
  { email: 'leticia.rocha.md@seed.castlight.app', name: 'Letícia Rocha', role: 'model', city: 'Recife', state: 'PE', country: 'BR', bio: 'Modelo e influenciadora de moda. Conteúdo para redes sociais e campanhas digitais. 80K seguidores. Parcerias e TFP seletivo.', styles: ['Fashion', 'Lifestyle', 'Beauty', 'Commercial'], instagram: '@leticiarochamd', avatar_url: 'https://images.unsplash.com/photo-1539367628448-4bc5c9d171c8?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'premium', verified_level: 'email', rating_avg: 4.6, total_reviews: 15, total_sessions: 19, measurements: '{"height":"169","bust":"84","waist":"64","hips":"90","shoes":"37","eyes":"Brown","hair":"Black"}' },
  { email: 'lucas.pereira.md@seed.castlight.app', name: 'Lucas Pereira', role: 'model', city: 'Florianópolis', state: 'SC', country: 'BR', bio: 'Modelo de moda praia masculina. Surfista e amante da natureza. Corpo bronzeado o ano todo. Ensaios em praias de SC.', styles: ['Fashion', 'Lifestyle', 'Fitness', 'Commercial'], instagram: '@lucaspereiramd', avatar_url: 'https://images.unsplash.com/photo-1557862921-37829c790f19?w=400&h=400&fit=crop&crop=face', user_level: 'starter', plan: 'free', verified_level: 'email', rating_avg: 4.3, total_reviews: 7, total_sessions: 9, measurements: '{"height":"181","bust":"98","waist":"76","hips":"94","shoes":"42","eyes":"Brown","hair":"Blonde"}' },
  { email: 'clara.mendes.md@seed.castlight.app', name: 'Clara Mendes', role: 'model', city: 'Belo Horizonte', state: 'MG', country: 'BR', bio: 'Modelo petite (1.63m) e orgulhosa! Provo que talento não tem tamanho mínimo. Editoriais criativos e campanhas para marcas que quebram padrões.', styles: ['Editorial', 'Fashion', 'Conceptual', 'Portrait'], instagram: '@claramendesmd', avatar_url: 'https://images.unsplash.com/photo-1557053910-d9eadeed1c58?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'free', verified_level: 'email', rating_avg: 4.6, total_reviews: 13, total_sessions: 16, measurements: '{"height":"163","bust":"80","waist":"60","hips":"86","shoes":"35","eyes":"Brown","hair":"Brown"}' },
  { email: 'raquel.dias.md@seed.castlight.app', name: 'Raquel Dias', role: 'model', city: 'Manaus', state: 'AM', country: 'BR', bio: 'Modelo indígena representando a beleza amazônica. Meus traços são minha identidade. Projetos artísticos e editoriais de moda sustentável. 🌿', styles: ['Fine Art', 'Editorial', 'Conceptual', 'Fashion'], instagram: '@raqueldiasmd', avatar_url: 'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?w=400&h=400&fit=crop&crop=face', user_level: 'starter', plan: 'free', verified_level: 'email', rating_avg: 4.5, total_reviews: 10, total_sessions: 13, measurements: '{"height":"166","bust":"82","waist":"62","hips":"88","shoes":"36","eyes":"Brown","hair":"Black"}' },
  { email: 'felipe.nunes.md@seed.castlight.app', name: 'Felipe Nunes', role: 'model', city: 'São Paulo', state: 'SP', country: 'BR', bio: 'Modelo andrógino e genderfluid. Quebro fronteiras de gênero na moda. Editoriais ousados, conceituais e sem limites. 🌈', styles: ['Fashion', 'Conceptual', 'Editorial', 'Fine Art'], instagram: '@felipenunesmd', avatar_url: 'https://images.unsplash.com/photo-1542909168-180c6d266f97?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'premium', verified_level: 'email', rating_avg: 4.7, total_reviews: 16, total_sessions: 20, measurements: '{"height":"176","bust":"88","waist":"68","hips":"90","shoes":"40","eyes":"Brown","hair":"Black"}' },

  // Creatives BR (5)
  { email: 'amanda.makeup2@seed.castlight.app', name: 'Amanda Lopes', role: 'creative', city: 'São Paulo', state: 'SP', country: 'BR', bio: 'Makeup artist especialista em pele negra. Colorimetria avançada e técnicas de contorno. Kit profissional MAC e MUFE.', styles: ['Beauty', 'Fashion', 'Editorial', 'Commercial'], instagram: '@amandalopesmua', avatar_url: 'https://images.unsplash.com/photo-1596215143922-aedfb3045e6b?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'premium', verified_level: 'email', rating_avg: 4.8, total_reviews: 22, total_sessions: 28 },
  { email: 'fernanda.stylist2@seed.castlight.app', name: 'Fernanda Tavares', role: 'creative', city: 'Rio de Janeiro', state: 'RJ', country: 'BR', bio: 'Produtora de moda e stylist. Lookbooks, catálogos e editoriais. Acervo de acessórios vintage e peças de alta costura.', styles: ['Fashion', 'Editorial', 'Commercial', 'Lifestyle'], instagram: '@fernandatavaresstylist', avatar_url: 'https://images.unsplash.com/photo-1598550874175-4d0ef436c909?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'free', verified_level: 'email', rating_avg: 4.5, total_reviews: 11, total_sessions: 14 },
  { email: 'ricardo.cenografo@seed.castlight.app', name: 'Ricardo Azevedo', role: 'creative', city: 'Curitiba', state: 'PR', country: 'BR', bio: 'Cenógrafo e diretor de arte. Transformo espaços comuns em cenários extraordinários para ensaios fotográficos e audiovisual.', styles: ['Conceptual', 'Commercial', 'Editorial', 'Fine Art'], instagram: '@ricardoazevedoart', avatar_url: 'https://images.unsplash.com/photo-1548449112-96a38a643324?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'pro', verified_level: 'email', rating_avg: 4.9, total_reviews: 27, total_sessions: 33 },

  // Dual BR (3)
  { email: 'camila.dual@seed.castlight.app', name: 'Camila Duarte', role: 'dual', city: 'São Paulo', state: 'SP', country: 'BR', bio: 'Fotógrafa e modelo. Autorretrato é minha especialidade. Quando modelo, trago direção criativa. Quando fotografo, entendo a modelo.', styles: ['Portrait', 'Fine Art', 'Fashion', 'Conceptual'], instagram: '@camiladuartedual', avatar_url: 'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'premium', verified_level: 'email', rating_avg: 4.6, total_reviews: 14, total_sessions: 18, equipment: ['Canon R6', 'RF 85mm f/2'], has_studio: false, languages: ['Portuguese', 'English'], measurements: '{"height":"168","bust":"82","waist":"62","hips":"88","shoes":"37","eyes":"Brown","hair":"Brown"}' },
  { email: 'fabio.dual@seed.castlight.app', name: 'Fábio Almeida', role: 'dual', city: 'Belo Horizonte', state: 'MG', country: 'BR', bio: 'Fotógrafo e modelo masculino. Dos dois lados da câmera com a mesma paixão. Editorial, streetwear e lifestyle.', styles: ['Fashion', 'Street', 'Editorial', 'Portrait'], instagram: '@fabioalmeidadual', avatar_url: 'https://images.unsplash.com/photo-1584999734482-0361aecad844?w=400&h=400&fit=crop&crop=face', user_level: 'starter', plan: 'free', verified_level: 'email', rating_avg: 4.4, total_reviews: 8, total_sessions: 10, equipment: ['Sony A6400', 'Sigma 30mm f/1.4'], has_studio: false, languages: ['Portuguese'], measurements: '{"height":"180","bust":"96","waist":"76","hips":"92","shoes":"42","eyes":"Brown","hair":"Black"}' },

  // ==================== USA BATCH 2 (30) ====================
  // Photographers US (10)
  { email: 'brandon.scott@seed.castlight.app', name: 'Brandon Scott', role: 'photographer', city: 'Los Angeles', state: 'CA', country: 'US', bio: 'Cinematic portrait photographer. My images tell stories. Inspired by film noir and golden age Hollywood. Studio in DTLA.', styles: ['Portrait', 'Fine Art', 'Editorial', 'Conceptual'], instagram: '@brandonscottphoto', avatar_url: 'https://images.unsplash.com/photo-1600486913747-55e5470d6f40?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'pro', verified_level: 'identity', rating_avg: 4.9, total_reviews: 37, total_sessions: 46, equipment: ['RED Komodo', 'Canon R5', 'Aputure 600d'], has_studio: true, languages: ['English'] },
  { email: 'hannah.kim.ph@seed.castlight.app', name: 'Hannah Kim', role: 'photographer', city: 'New York', state: 'NY', country: 'US', bio: 'Korean-American photographer specializing in beauty and cosmetics campaigns. Clients include Glossier, Fenty Beauty, and K-beauty brands.', styles: ['Beauty', 'Commercial', 'Fashion', 'Editorial'], instagram: '@hannahkimphoto', avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'pro', verified_level: 'identity', rating_avg: 4.8, total_reviews: 32, total_sessions: 40, equipment: ['Phase One IQ4', 'Broncolor Siros'], has_studio: true, languages: ['English', 'Korean'] },
  { email: 'derek.williams.ph@seed.castlight.app', name: 'Derek Williams', role: 'photographer', city: 'Houston', state: 'TX', country: 'US', bio: 'Hip-hop and music photographer. Capturing the energy of live shows and artist portraits. Also available for fashion and editorial.', styles: ['Portrait', 'Editorial', 'Events', 'Street'], instagram: '@derekwilliamsphoto', avatar_url: 'https://images.unsplash.com/photo-1590086783191-a0694c7d1e6e?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'premium', verified_level: 'email', rating_avg: 4.6, total_reviews: 16, total_sessions: 20, equipment: ['Sony A9 III', 'GM 24-70mm f/2.8'], has_studio: false, languages: ['English'] },
  { email: 'ashley.moore.ph@seed.castlight.app', name: 'Ashley Moore', role: 'photographer', city: 'Phoenix', state: 'AZ', country: 'US', bio: 'Desert landscape and portrait photographer. Golden hour specialist. Creating ethereal images in the Arizona desert. 🌵✨', styles: ['Portrait', 'Lifestyle', 'Fine Art', 'Fashion'], instagram: '@ashleymoorphoto', avatar_url: 'https://images.unsplash.com/photo-1614283233556-f35b0c801ef1?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'free', verified_level: 'email', rating_avg: 4.5, total_reviews: 13, total_sessions: 17, equipment: ['Canon R6 III', 'RF 50mm f/1.2'], has_studio: false, languages: ['English'] },
  { email: 'michael.chang.ph@seed.castlight.app', name: 'Michael Chang', role: 'photographer', city: 'San Diego', state: 'CA', country: 'US', bio: 'Fitness and bodybuilding photographer. Former athlete. I understand the discipline behind the physique. Studio shoots and gym sessions.', styles: ['Fitness', 'Commercial', 'Portrait', 'Lifestyle'], instagram: '@michaelchangphoto', avatar_url: 'https://images.unsplash.com/photo-1504257432389-52343af06ae3?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'pro', verified_level: 'identity', rating_avg: 4.9, total_reviews: 39, total_sessions: 48, equipment: ['Nikon Z9', 'Profoto B10', 'Elinchrom ELC 500'], has_studio: true, languages: ['English', 'Mandarin'] },
  { email: 'kelly.green.ph@seed.castlight.app', name: 'Kelly Green', role: 'photographer', city: 'Portland', state: 'OR', country: 'US', bio: 'Moody editorial and fine art photographer. Dark tones, dramatic lighting, and emotional storytelling. PNW vibes all day.', styles: ['Fine Art', 'Editorial', 'Portrait', 'Conceptual'], instagram: '@kellygreenphoto', avatar_url: 'https://images.unsplash.com/photo-1611432579699-484f7990b127?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'premium', verified_level: 'email', rating_avg: 4.7, total_reviews: 18, total_sessions: 23, equipment: ['Sony A7IV', 'Sigma 35mm f/1.4 Art'], has_studio: true, languages: ['English'] },
  { email: 'jason.lee.ph@seed.castlight.app', name: 'Jason Lee', role: 'photographer', city: 'Las Vegas', state: 'NV', country: 'US', bio: 'Glamour and boudoir photographer. 15 years experience. Safe, professional environment. Empowering women through beautiful imagery.', styles: ['Boudoir', 'Beauty', 'Portrait', 'Fashion'], instagram: '@jasonleephoto', avatar_url: 'https://images.unsplash.com/photo-1507081323647-4d250478b919?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'pro', verified_level: 'identity', rating_avg: 4.8, total_reviews: 35, total_sessions: 44, equipment: ['Canon R5', 'Profoto B1X', 'Profoto D2'], has_studio: true, languages: ['English'] },
  { email: 'natalie.brown.ph@seed.castlight.app', name: 'Natalie Brown', role: 'photographer', city: 'Minneapolis', state: 'MN', country: 'US', bio: 'Natural light specialist. Intimate, soft, and dreamy portraits. Shooting in vintage locations around the Twin Cities.', styles: ['Portrait', 'Couples', 'Lifestyle', 'Fine Art'], instagram: '@nataliebrownphoto', avatar_url: 'https://images.unsplash.com/photo-1597223557154-721c1cecc4b0?w=400&h=400&fit=crop&crop=face', user_level: 'starter', plan: 'free', verified_level: 'email', rating_avg: 4.4, total_reviews: 9, total_sessions: 12, equipment: ['Fujifilm X-H2S', 'XF 56mm f/1.2'], has_studio: false, languages: ['English'] },
  { email: 'ryan.patel.ph@seed.castlight.app', name: 'Ryan Patel', role: 'photographer', city: 'Charlotte', state: 'NC', country: 'US', bio: 'Product and catalog photographer. Also shoot editorials and lookbooks for fashion brands. Clean, modern aesthetic.', styles: ['Commercial', 'Fashion', 'Editorial', 'Beauty'], instagram: '@ryanpatelphoto', avatar_url: 'https://images.unsplash.com/photo-1564564295391-7f24f26f568b?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'free', verified_level: 'email', rating_avg: 4.5, total_reviews: 11, total_sessions: 14, equipment: ['Canon R5', 'RF 100mm f/2.8 Macro'], has_studio: true, languages: ['English', 'Hindi'] },
  { email: 'samantha.jones.ph@seed.castlight.app', name: 'Samantha Jones', role: 'photographer', city: 'Tampa', state: 'FL', country: 'US', bio: 'Maternity, newborn, and family photographer. Capturing the most precious moments in life. Warm, inviting studio space.', styles: ['Maternity', 'Portrait', 'Lifestyle', 'Fine Art'], instagram: '@samanthajonesphoto', avatar_url: 'https://images.unsplash.com/photo-1589571894960-20bbe2828d0a?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'premium', verified_level: 'email', rating_avg: 4.8, total_reviews: 28, total_sessions: 35, equipment: ['Nikon Z6 III', 'Nikkor 85mm f/1.4'], has_studio: true, languages: ['English'] },

  // Models US (12)
  { email: 'taylor.swift.md@seed.castlight.app', name: 'Taylor Reed', role: 'model', city: 'Los Angeles', state: 'CA', country: 'US', bio: 'High fashion model. 5\'11". Runway and editorial focused. Represented by Next Models LA. Selective TFP for artistic projects.', styles: ['Fashion', 'Editorial', 'Fine Art', 'Conceptual'], instagram: '@taylorreedmodel', avatar_url: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'pro', verified_level: 'identity', rating_avg: 4.9, total_reviews: 40, total_sessions: 50, measurements: '{"height":"180","bust":"84","waist":"60","hips":"88","shoes":"9.5","eyes":"Blue","hair":"Blonde"}' },
  { email: 'marcus.johnson.md@seed.castlight.app', name: 'Marcus Johnson', role: 'model', city: 'Atlanta', state: 'GA', country: 'US', bio: 'Male model and actor. 6\'1". Athletic build. Experience in commercial, catalog, and editorial work. SAG eligible.', styles: ['Commercial', 'Fashion', 'Fitness', 'Editorial'], instagram: '@marcusjohnsonmodel', avatar_url: 'https://images.unsplash.com/photo-1506277886164-e25aa3f4ef7f?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'pro', verified_level: 'identity', rating_avg: 4.8, total_reviews: 29, total_sessions: 36, measurements: '{"height":"185","bust":"102","waist":"78","hips":"96","shoes":"12","eyes":"Brown","hair":"Black"}' },
  { email: 'olivia.white.md@seed.castlight.app', name: 'Olivia White', role: 'model', city: 'Miami', state: 'FL', country: 'US', bio: 'Swimwear model and brand ambassador. Perpetual summer vibes. 🌴 Available for beachwear, resort, and lifestyle campaigns.', styles: ['Fashion', 'Lifestyle', 'Commercial', 'Beauty'], instagram: '@oliviawhitemodel', avatar_url: 'https://images.unsplash.com/photo-1469460340997-2f854421e72f?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'premium', verified_level: 'email', rating_avg: 4.7, total_reviews: 20, total_sessions: 26, measurements: '{"height":"172","bust":"86","waist":"64","hips":"92","shoes":"8","eyes":"Green","hair":"Brown"}' },
  { email: 'daniel.garcia.md@seed.castlight.app', name: 'Daniel Garcia', role: 'model', city: 'San Antonio', state: 'TX', country: 'US', bio: 'Latino model breaking into the industry. 6\'0". Versatile look — can pull off rugged outdoor to sleek editorial. Let\'s create!', styles: ['Fashion', 'Editorial', 'Lifestyle', 'Portrait'], instagram: '@danielgarciamodel', avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face', user_level: 'starter', plan: 'free', verified_level: 'email', rating_avg: 4.4, total_reviews: 8, total_sessions: 11, measurements: '{"height":"183","bust":"98","waist":"78","hips":"94","shoes":"11","eyes":"Brown","hair":"Black"}' },
  { email: 'jasmine.patel.md@seed.castlight.app', name: 'Jasmine Patel', role: 'model', city: 'Chicago', state: 'IL', country: 'US', bio: 'South Asian model representing diversity in fashion. 5\'8". Experienced in beauty, bridal, and editorial campaigns.', styles: ['Beauty', 'Fashion', 'Editorial', 'Commercial'], instagram: '@jasminepatelmodel', avatar_url: 'https://images.unsplash.com/photo-1617258683320-61900b281ced?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'premium', verified_level: 'email', rating_avg: 4.6, total_reviews: 15, total_sessions: 19, measurements: '{"height":"173","bust":"84","waist":"62","hips":"90","shoes":"8","eyes":"Brown","hair":"Black"}' },
  { email: 'connor.murphy.md@seed.castlight.app', name: 'Connor Murphy', role: 'model', city: 'Boston', state: 'MA', country: 'US', bio: 'Fitness model and YouTuber. Natural physique, clean-cut look. Experience with supplement, sportswear, and lifestyle brands.', styles: ['Fitness', 'Commercial', 'Lifestyle', 'Portrait'], instagram: '@connormurphyfit', avatar_url: 'https://images.unsplash.com/photo-1519058082700-08a0b56da9b4?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'free', verified_level: 'email', rating_avg: 4.5, total_reviews: 12, total_sessions: 16, measurements: '{"height":"185","bust":"104","waist":"78","hips":"96","shoes":"11.5","eyes":"Blue","hair":"Brown"}' },
  { email: 'maya.jackson.md@seed.castlight.app', name: 'Maya Jackson', role: 'model', city: 'Washington', state: 'DC', country: 'US', bio: 'Curve model and body positivity influencer. Size 16. Featured in Cosmopolitan and Refinery29. Booking TFP for art projects.', styles: ['Fashion', 'Editorial', 'Lifestyle', 'Commercial'], instagram: '@mayajacksonmodel', avatar_url: 'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'premium', verified_level: 'identity', rating_avg: 4.8, total_reviews: 25, total_sessions: 31, measurements: '{"height":"175","bust":"106","waist":"84","hips":"114","shoes":"9","eyes":"Brown","hair":"Black"}' },
  { email: 'ethan.clark.md@seed.castlight.app', name: 'Ethan Clark', role: 'model', city: 'San Francisco', state: 'CA', country: 'US', bio: 'Androgynous model. Fashion is for everyone. Blurring the lines between masculine and feminine. Editorial and conceptual only.', styles: ['Conceptual', 'Editorial', 'Fashion', 'Fine Art'], instagram: '@ethanclarkmodel', avatar_url: 'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?w=400&h=400&fit=crop&crop=face', user_level: 'starter', plan: 'free', verified_level: 'email', rating_avg: 4.4, total_reviews: 9, total_sessions: 12, measurements: '{"height":"178","bust":"90","waist":"70","hips":"90","shoes":"10","eyes":"Green","hair":"Blonde"}' },
  { email: 'isabella.santos.md@seed.castlight.app', name: 'Isabella Santos', role: 'model', city: 'Orlando', state: 'FL', country: 'US', bio: 'Brazilian-American model bridging two cultures. Bilingual. Available for fashion, beauty, and commercial campaigns in Florida.', styles: ['Fashion', 'Beauty', 'Commercial', 'Lifestyle'], instagram: '@isabellasantosmodel', avatar_url: 'https://images.unsplash.com/photo-1524638431109-93d95c968f03?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'free', verified_level: 'email', rating_avg: 4.6, total_reviews: 14, total_sessions: 18, measurements: '{"height":"170","bust":"84","waist":"62","hips":"90","shoes":"7.5","eyes":"Brown","hair":"Brown"}' },
  { email: 'logan.harris.md@seed.castlight.app', name: 'Logan Harris', role: 'model', city: 'Dallas', state: 'TX', country: 'US', bio: 'Country-meets-fashion model. 6\'2". Southern charm with a high fashion edge. Cowboy boots to designer suits. 🤠', styles: ['Fashion', 'Lifestyle', 'Commercial', 'Editorial'], instagram: '@loganharrismodel', avatar_url: 'https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'premium', verified_level: 'email', rating_avg: 4.5, total_reviews: 11, total_sessions: 14, measurements: '{"height":"188","bust":"100","waist":"78","hips":"96","shoes":"12","eyes":"Blue","hair":"Brown"}' },
  { email: 'grace.kim.md@seed.castlight.app', name: 'Grace Kim', role: 'model', city: 'Seattle', state: 'WA', country: 'US', bio: 'Korean-American model. Skincare and beauty specialist. Featured in Allure and Vogue Korea. Looking for creative TFP in the PNW.', styles: ['Beauty', 'Fashion', 'Editorial', 'Commercial'], instagram: '@gracekimmodel', avatar_url: 'https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'pro', verified_level: 'identity', rating_avg: 4.9, total_reviews: 34, total_sessions: 42, measurements: '{"height":"168","bust":"82","waist":"60","hips":"86","shoes":"7","eyes":"Brown","hair":"Black"}' },
  { email: 'ryan.chen.md@seed.castlight.app', name: 'Ryan Chen', role: 'model', city: 'New York', state: 'NY', country: 'US', bio: 'Asian-American male model. 6\'0". Breaking stereotypes in the fashion industry. GQ, Esquire, and Men\'s Health featured.', styles: ['Fashion', 'Editorial', 'Commercial', 'Fitness'], instagram: '@ryanchenmodel', avatar_url: 'https://images.unsplash.com/photo-1545167622-3a6ac756afa4?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'pro', verified_level: 'identity', rating_avg: 4.8, total_reviews: 28, total_sessions: 35, measurements: '{"height":"183","bust":"98","waist":"76","hips":"94","shoes":"10.5","eyes":"Brown","hair":"Black"}' },

  // Creatives US (5)
  { email: 'victoria.mua@seed.castlight.app', name: 'Victoria Reyes', role: 'creative', city: 'Los Angeles', state: 'CA', country: 'US', bio: 'Celebrity MUA. Worked with A-list clients for red carpet events. SFX, beauty, editorial — I do it all. Open to TFP for portfolio pieces.', styles: ['Beauty', 'Fashion', 'Editorial', 'Commercial'], instagram: '@victoriareymua', avatar_url: 'https://images.unsplash.com/photo-1581403341630-a6e0b9d2d257?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'pro', verified_level: 'identity', rating_avg: 4.9, total_reviews: 38, total_sessions: 47 },
  { email: 'amber.stylist2@seed.castlight.app', name: 'Amber Collins', role: 'creative', city: 'New York', state: 'NY', country: 'US', bio: 'Celebrity wardrobe stylist. Pulls from top designers. Music video, editorial, and commercial styling. Vogue contributor.', styles: ['Fashion', 'Editorial', 'Commercial', 'Lifestyle'], instagram: '@ambercollinsstyle', avatar_url: 'https://images.unsplash.com/photo-1573497019236-17f8177b81e8?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'pro', verified_level: 'email', rating_avg: 4.8, total_reviews: 30, total_sessions: 37 },
  { email: 'carlos.sfx@seed.castlight.app', name: 'Carlos Mendez', role: 'creative', city: 'Miami', state: 'FL', country: 'US', bio: 'SFX makeup and prosthetics artist. Film, TV, and editorial horror/fantasy. Transform anyone into anything. Let\'s get weird! 🎃', styles: ['Conceptual', 'Editorial', 'Fine Art', 'Beauty'], instagram: '@carlosmendezsfx', avatar_url: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'premium', verified_level: 'email', rating_avg: 4.7, total_reviews: 19, total_sessions: 24 },
  { email: 'diana.nails2@seed.castlight.app', name: 'Diana Flores', role: 'creative', city: 'Houston', state: 'TX', country: 'US', bio: 'Nail artist for editorial and advertising. Sculpted nails, 3D art, chrome effects. My nails have been in Allure and NYLON.', styles: ['Beauty', 'Editorial', 'Fashion', 'Commercial'], instagram: '@dianafloresnails', avatar_url: 'https://images.unsplash.com/photo-1601288496920-b6154fe3626a?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'free', verified_level: 'email', rating_avg: 4.6, total_reviews: 13, total_sessions: 17 },
  { email: 'kevin.setdesign2@seed.castlight.app', name: 'Kevin Park', role: 'creative', city: 'Los Angeles', state: 'CA', country: 'US', bio: 'Set designer and prop stylist for photo and film. From minimalist white box to elaborate fantasy worlds. Your vision, my execution.', styles: ['Commercial', 'Conceptual', 'Editorial', 'Fashion'], instagram: '@kevinparksets', avatar_url: 'https://images.unsplash.com/photo-1557862921-37829c790f19?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'premium', verified_level: 'email', rating_avg: 4.8, total_reviews: 22, total_sessions: 28 },

  // Dual US (3)
  { email: 'sierra.dual@seed.castlight.app', name: 'Sierra Davis', role: 'dual', city: 'Los Angeles', state: 'CA', country: 'US', bio: 'Photographer and model. Creative director who understands both sides of the camera. Self-portrait artist and workshop teacher.', styles: ['Portrait', 'Fashion', 'Fine Art', 'Conceptual'], instagram: '@sierradavisdual', avatar_url: 'https://images.unsplash.com/photo-1542596768-5d1d21f1cf98?w=400&h=400&fit=crop&crop=face', user_level: 'established', plan: 'pro', verified_level: 'identity', rating_avg: 4.8, total_reviews: 26, total_sessions: 32, equipment: ['Canon R5', 'RF 85mm f/1.2'], has_studio: true, languages: ['English'], measurements: '{"height":"172","bust":"84","waist":"62","hips":"90","shoes":"8","eyes":"Brown","hair":"Black"}' },
  { email: 'mason.dual@seed.castlight.app', name: 'Mason Rivera', role: 'dual', city: 'Miami', state: 'FL', country: 'US', bio: 'Model-turned-photographer. 6\'1". My modeling experience makes me a better photographer — I know how to direct and how to pose.', styles: ['Fashion', 'Editorial', 'Portrait', 'Lifestyle'], instagram: '@masonriveradual', avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face', user_level: 'rising', plan: 'premium', verified_level: 'email', rating_avg: 4.6, total_reviews: 14, total_sessions: 18, equipment: ['Sony A7C II', 'Tamron 35mm'], has_studio: false, languages: ['English', 'Spanish'], measurements: '{"height":"185","bust":"100","waist":"78","hips":"96","shoes":"11","eyes":"Brown","hair":"Brown"}' },
];

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const authHeader = req.headers.get("Authorization");
    if (!authHeader) {
      return new Response(JSON.stringify({ error: "No auth" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const anonKey = Deno.env.get("SUPABASE_ANON_KEY")!;

    const userClient = createClient(supabaseUrl, anonKey, { global: { headers: { Authorization: authHeader } } });
    const { data: { user }, error: userError } = await userClient.auth.getUser();
    if (userError || !user) {
      return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const adminClient = createClient(supabaseUrl, serviceRoleKey);
    const { data: roleData } = await adminClient.from("user_roles").select("role").eq("user_id", user.id).eq("role", "admin").single();
    if (!roleData) {
      return new Response(JSON.stringify({ error: "Admin required" }), { status: 403, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const results: any[] = [];
    const errors: any[] = [];

    for (const seedUser of SEED_USERS) {
      try {
        const { data: authData, error: authError } = await adminClient.auth.admin.createUser({
          email: seedUser.email,
          password: 'SeedUser2026!',
          email_confirm: true,
          user_metadata: { name: seedUser.name },
        });

        if (authError) {
          if (authError.message?.includes('already been registered')) {
            results.push({ email: seedUser.email, status: 'already_exists' });
            continue;
          }
          throw authError;
        }

        const userId = authData.user.id;

        const profileUpdate: any = {
          name: seedUser.name,
          role: seedUser.role,
          city: seedUser.city,
          state: seedUser.state,
          country: seedUser.country,
          bio: seedUser.bio,
          styles: seedUser.styles,
          instagram: seedUser.instagram,
          avatar_url: seedUser.avatar_url,
          is_seed: true,
          is_active: true,
          onboarding_completed: true,
          user_level: seedUser.user_level || 'newcomer',
          plan: seedUser.plan || 'free',
          verified_level: seedUser.verified_level || 'none',
          rating_avg: seedUser.rating_avg || 0,
          total_reviews: seedUser.total_reviews || 0,
          total_sessions: seedUser.total_sessions || 0,
          available_now: Math.random() > 0.6,
          last_active: new Date(Date.now() - Math.floor(Math.random() * 86400000 * 3)).toISOString(),
        };

        if (seedUser.equipment) profileUpdate.equipment = seedUser.equipment;
        if (seedUser.has_studio !== undefined) profileUpdate.has_studio = seedUser.has_studio;
        if (seedUser.languages) profileUpdate.languages = seedUser.languages;
        if ((seedUser as any).measurements) profileUpdate.measurements = JSON.parse((seedUser as any).measurements);

        const { error: profileError } = await adminClient.from("profiles").update(profileUpdate).eq("id", userId);
        if (profileError) throw profileError;

        results.push({ email: seedUser.email, id: userId, status: 'created', country: seedUser.country });
      } catch (err: any) {
        errors.push({ email: seedUser.email, error: err.message });
      }
    }

    const brCount = results.filter(r => r.status === 'created' && r.country === 'BR').length;
    const usCount = results.filter(r => r.status === 'created' && r.country === 'US').length;

    return new Response(JSON.stringify({ created: results.filter(r => r.status === 'created').length, br: brCount, us: usCount, existing: results.filter(r => r.status === 'already_exists').length, errors: errors.length, details: { results, errors } }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (err: any) {
    return new Response(JSON.stringify({ error: err.message }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
