#!/usr/bin/env bash
# Bundle a Supabase edge function with its _shared deps into a single file.
# Usage: bundle-edge-fn.sh <function-name>
# Output: prints the bundled TypeScript to stdout.
#
# Strips internal cross-module imports (the `import ... from "../_shared/..."`
# lines and `import type ... from "../*.ts"`) and the `export ` keyword from
# shared declarations, since after concatenation everything lives in one
# module scope. External imports (npm:, jsr:, https://, esm.sh, deno.land)
# pass through untouched.

set -euo pipefail

fn_name="${1:?missing function name}"
root="$(cd "$(dirname "$0")/.." && pwd)"
shared="$root/supabase/functions/_shared"
fn_root="$root/supabase/functions/$fn_name"
entrypoint="$fn_root/index.ts"

if [[ ! -f "$entrypoint" ]]; then
  echo "entrypoint not found: $entrypoint" >&2
  exit 1
fi

strip_local_imports() {
  # Remove `import ... from "(./|../)..."` lines (any whitespace, any spec).
  sed -E '/^import [^"]*"(\.\.?\/[^"]*)";?[[:space:]]*$/d'
}

strip_exports() {
  # Convert `export interface X` / `export function X` / `export const X` etc.
  # into bare declarations, since everything will live in one module scope.
  # Also drop `export type ... = ...;` (single line) and `export {...};`.
  sed -E \
    -e 's/^export interface /interface /' \
    -e 's/^export type /type /' \
    -e 's/^export function /function /' \
    -e 's/^export async function /async function /' \
    -e 's/^export const /const /' \
    -e 's/^export class /class /' \
    -e 's/^export \{/\/\/ removed re-export {/' \
    | sed -E '/^export \* from /d'
}

# Collect: shared files in dependency order, then the entrypoint.
# Order matters because we concatenate into one module: brand → brevo →
# templates/_layout → individual templates → entrypoint.
files=(
  "$shared/brand.ts"
  "$shared/brevo.ts"
  "$shared/templates/_layout.ts"
)

# Discover which templates the entrypoint imports, in declared order.
while IFS= read -r line; do
  # Match `from "../_shared/templates/<file>.ts"`
  if [[ "$line" =~ from\ \"\.\./_shared/templates/([^\"]+)\.ts\" ]]; then
    files+=("$shared/templates/${BASH_REMATCH[1]}.ts")
  fi
done < "$entrypoint"

echo "// Bundled $fn_name (deploy artifact — sources live in supabase/functions/_shared/)"
echo "// Generated by scripts/bundle-edge-fn.sh"
echo ""

for f in "${files[@]}"; do
  echo "// ── ${f#$root/} ──"
  < "$f" strip_local_imports | strip_exports
  echo ""
done

echo "// ── supabase/functions/$fn_name/index.ts ──"
< "$entrypoint" strip_local_imports | strip_exports
